### ISSUE TITLE
I cant add this to ScrollView

### ISSUE THREAD

**Issue by marindominikovic** [chiralcode/Android-Color-Picker#1]
It works in linearlayout, but when I ad it to ScrollView my app crashes.

04-19 16:24:16.542: E/AndroidRuntime(10188): java.lang.RuntimeException: Unable to start activity ComponentInfo{cro.marin.colorwallpaper/cro.marin.colorwallpaper.WallpaperColor}: java.lang.ClassCastException: android.widget.ScrollView

**Comment by zjamshidi** [comment]
I have the same problem.

**Comment by coddicted** [comment]
I am also getting error!
My error is:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1224)
at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:579)
at colorpicker.ColorPicker.onDraw(ColorPicker.java:153)
